#!/usr/bin/env bash
# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Disable strict host key checking for scp
scp_command="scp -o StrictHostKeyChecking=no -i $ssh_key $file_path $username@$server_ip:~/"

# Execute scp command
$scp_command
