#!/usr/bin/env bash
# Install Nginx and configures it on a remote server
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
